### ISSUE TITLE
Crash with 1.1.3

### ISSUE THREAD

**Issue by s1shed** [jaronmcd/rtl-haos#33]
After updating to 1.1.3:

``` 
ERROR: [RTL]: Error processing line: DataProcessor.dispatch_reading() got an unexpected keyword argument 'radio_freq'
```

Version 1.1 is working fine.

Seems it's caused by a partial revert. This will probably fix it.

```patch
diff --git a/rtl_manager.py b/rtl_manager.py
index 7f2ac2c..0b7808b 100644
--- a/rtl_manager.py
+++ b/rtl_manager.py
@@ -194,8 +194,8 @@ def rtl_loop(radio_config: dict, mqtt_handler, data_processor, sys_id: str, sys_
                     if "Neptune-R900" in model and data.get("consumption") is not None:
                         real_val = float(data["consumption"]) / 10.0
                         data_processor.dispatch_reading(
-                            clean_id, "meter_reading", real_val, dev_name, model, 
-                            radio_name=radio_name, radio_freq=freq_display
+                            clean_id, "meter_reading", real_val, dev_name, model,
+                            radio_name=radio_name
                         )
                         del data["consumption"] # Prevent duplicate sending
 
@@ -203,7 +203,7 @@ def rtl_loop(radio_config: dict, mqtt_handler, data_processor, sys_id: str, sys_
                     if ("SCM" in model or "ERT" in model) and data.get("consumption") is not None:
                         data_processor.dispatch_reading(
                             clean_id, "Consumption", data["consumption"], dev_name, model,
-                            radio_name=radio_name, radio_freq=freq_display
+                            radio_name=radio_name
                         )
                         del data["consumption"]
 
@@ -217,7 +217,7 @@ def rtl_loop(radio_config: dict, mqtt_handler, data_processor, sys_id: str, sys_
                         if dp_f is not None:
                             data_processor.dispatch_reading(
                                 clean_id, "dew_point", dp_f, dev_name, model,
-                                radio_name=radio_name, radio_freq=freq_display
+                                radio_name=radio_name
                             )
 
                     # --- 6. GENERIC FLATTEN & SEND ---
@@ -230,18 +230,18 @@ def rtl_loop(radio_config: dict, mqtt_handler, data_processor, sys_id: str, sys_
                             val_f = round(value * 1.8 + 32.0, 1)
                             data_processor.dispatch_reading(
                                 clean_id, "temperature", val_f, dev_name, model,
-                                radio_name=radio_name, radio_freq=freq_display
+                                radio_name=radio_name
                             )
                         elif key in ["temperature_F", "temp_F", "temperature"] and isinstance(value, (int, float)):
                             data_processor.dispatch_reading(
                                 clean_id, "temperature", value, dev_name, model,
-                                radio_name=radio_name, radio_freq=freq_display
+                                radio_name=radio_name
                             )
                         else:
                             # Catch-all dispatch
                             data_processor.dispatch_reading(
                                 clean_id, key, value, dev_name, model,
-                                radio_name=radio_name, radio_freq=freq_display
+                                radio_name=radio_name
                             )
 
                 except json.JSONDecodeError:
```

(Untested as I am new to HA and don't know how I can "live patch" on the server itself)

**Comment by jaronmcd** [comment]
thanks! 1.1.4 should fix it, it was a long day yesterday and I should have been paying more attention.

**Comment by DP042715** [comment]
Hey all! Not sure when but definitely before 1.13, my RTLHAOS stopped detecting my dongle and started giving me:
WARN: [STARTUP]: Warning: No hardware detected during scan.
I’m currently in 1.15 and despite unplugging and replugging, rebuilding and restarting the add on and restarting HAOS, I am still getting the warning above followed by a crash loop

[11:50:00] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...

Any insight here would be great!

It was working fine at the beginning when the RTLHAOS add-on repo went live for about a week or so.

**Comment by s1shed** [comment]
> thanks! 1.1.4 should fix it, it was a long day yesterday and I should have been paying more attention.

Working fine on 1.1.5 :)



> [11:50:00] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...

Hmm...I don't have any clue about this. :/

**Comment by jaronmcd** [comment]
> Hey all! Not sure when but definitely before 1.13, my RTLHAOS stopped detecting my dongle and started giving me: WARN: [STARTUP]: Warning: No hardware detected during scan. I’m currently in 1.15 and despite unplugging and replugging, rebuilding and restarting the add on and restarting HAOS, I am still getting the warning above followed by a crash loop
> 
> [11:50:00] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...
> 
> Any insight here would be great!
> 
> It was working fine at the beginning when the RTLHAOS add-on repo went live for about a week or so.

what's the full startup log look like?

**Comment by DP0427** [comment]
@jaronmcd Here's what the log looks like right after I did a Rebuilt > Restart, then up until the point it starts crash looping:

```
[18:19:48] INFO: Running in Home Assistant Add-on mode
[18:19:48] INFO: Using Home Assistant MQTT service
[18:19:48] INFO: Starting RTL-HAOS bridge...
[18:19:48] INFO: MQTT Host: core-mosquitto:1883
[18:19:49] INFO: [CONFIG]: Success! Loaded settings from Home Assistant.
   ____  _____  _         _   _    _    ___  ____  
  |  _ \|_   _|| |       | | | |  / \  / _ \/ ___| 
  | |_) | | |  | |  ___  | |_| | / _ \| | | \___ \ 
  |  _ <  | |  | | |___| |  _  |/ ___ \ |_| |___) |
  |_| \_\ |_|  |_____|   |_| |_/_/   \_\___/|____/ 
>>> RTL-SDR Bridge for Home Assistant (v1.1.5) <<<
[18:19:52] INFO: [STARTUP]: Connecting to MQTT Broker at core-mosquitto...
[18:19:52] INFO: [THROTTLE]: Averaging data every 30 seconds.[18:19:52] INFO: [STARTUP]: Scanning USB bus for RTL-SDR devices...
[18:19:52] WARN: [STARTUP]: Warning: No hardware detected during scan.
[18:19:52] INFO: [STARTUP]: No serials detected. Defaulting to generic device '0'.
[18:19:52] INFO: [RTL]: Starting RTL_auto on 433.92M (Rate: 250k)...
[18:19:52] INFO: [MQTT]: Connected Successfully.
[18:19:52] INFO: [STARTUP]: Hardware Monitor (psutil) initialized.[18:19:52] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...
[18:19:52] INFO: [STARTUP]: Starting System Monitor Loop...
[18:19:57] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...
[18:20:02] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...
[18:20:07] ERROR: [RTL]: RTL_auto crashed/stopped. Restarting in 5s...
```

**Comment by jaronmcd** [comment]
it seems it can't find the rtl-sdr? How are you running it? If standalone, check lsusb to see if the rtl-sdr shows up, if it does, you might have a permission issue requiring system level changes or try a hardware restart.

**Comment by jaronmcd** [comment]
FYI: 1.0.8 has better error reporting, but I am not sure if it will show anything new because in your case it seems your hardware is not detected.

**Comment by DP042715** [comment]
Hi all, I was able to figure it out. The USB 2.0 extension cable despite working for awhile seems to not deliver enough power to the RTL2832 dongle. After testing that it worked fine for listening to FM radio on windows (using Airspy) directly plugged into the PC, I eventually got my NUC to recognize the connection when it’s directly plugged into the USB3.0 ports. 

Now my dilemma is worrying about noise as I may need a powered USB extension if I want to get the dongle away from the NUC eventually.

So TLDR: completely hardware related. Apologies! Keep up the good work!

**Comment by jaronmcd** [comment]
Sweet! Glad you figured it out! You could try to remove rtl-haos as an add on and try to run standalone on a raspberry pi. Then the raspberry pi could connect to HAOS MQTT via WIFI and be placed away from any noise sources.

**Comment by jaronmcd** [comment]
closing this issue because all seems to be good
